[package]
name = "auth_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "auth_service"
path = "src/service.rs"

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = [ "clock", "std" ] }
rdkafka = { version = "0.28", features = ["cmake-build"] }
jsonwebtoken = "8.0.1"
lazy_static = "1.4.0"
serde = "1.0.136"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "0.8.2", features = ["v4"] }
bcrypt = "0.12.0"
rs-auth = { git = "https://github.com/MSOStream/rs-auth" }
prost = "0.10"
tonic = { version = "0.7", features = ["compression"] }
redis = { version = "0.21.5", features = ["r2d2"] }
r2d2 = "0.8.9"

[build-dependencies]
tonic-build = "0.7"