[package]
name = "auth_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "auth_service"
path = "src/service.rs"

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = [ "clock", "std" ] }
jsonwebtoken = "8.0.1"
lazy_static = "1.4.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
prost = "0.9.0"
serde = "1.0.136"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.6.2"
uuid = { version = "0.8.2", features = ["v4"] }
diesel = { version = "1.4.8", features = ["postgres", "chrono"] }
diesel_migrations = "1.4.0"
bcrypt = "0.12.0"

[build-dependencies]
tonic-build = "0.6.2"
