image: 
  file: .gitpod.dockerfile
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
  - port: 9001
    onOpen: open-preview
tasks:
  - name: Dependencies & Database
    init: |
      mv backend/Rocket.toml backend/Rocket.toml.BAK
      mv backend/Rocket.toml.gitpod backend/Rocket.toml
      sudo apt-get update -y
      sudo apt-get -y install pkg-config libssl-dev libpq-dev
      sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
      rustup default nightly
      cargo install diesel_cli --no-default-features --features postgres
      cd backend/postgres
      cp src/schema.rs src/schema.rs.BAK
      diesel migration run
      rm src/schema.rs
      mv src/schema.rs.BAK src/schema.rs
    command: |
      echo "Hello to Projektkurs-Mono!"
  - name: Minio
    init: |
      wget https://dl.min.io/server/minio/release/linux-amd64/minio
      sudo chmod +x minio
    command: |
      sudo mkdir /data
      sudo chown -R gitpod /data && sudo chmod u+rxw /data
      MINIO_ROOT_USER=minio-admin MINIO_ROOT_PASSWORD=strongPassword ./minio server /data --console-address ":9001"
  - name: Frontend
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      REACT_APP_WORKSPACE_URL=$GITPOD_WORKSPACE_URL npm start
  - name: Backend
    init: |
      cd backend
      cargo build
    command: |
      cd backend
      gp await-port 9000
      gp await-port 5432
      cargo run