image: gitpod/workspace-postgres
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
  - port: 9001
    onOpen: open-preview
tasks:
  - name: Projektkurs-Mono
    init: |
      mkdir /data
      chown -R gitpod /data && sudo chmod u+rxw /data
      wget https://dl.min.io/server/minio/release/linux-amd64/minio
      chmod +x minio
      MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=strongPassword ./minio server /data --console-address ":9001" &
      apt-get update -y
      apt-get -y install postgresql pkg-config libssl-dev ffmpeg libpq-dev
      systemctl stop postgresql.service
      systemctl start postgresql.service
      systemctl enable postgresql.service
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      rustup default nightly
      cargo install diesel_cli --no-default-features --features postgres 
    command: |
      echo "Hello to Projektkurs-Mono!"
