image: ubuntu:21.10
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
  - port: 9001
    onOpen: open-preview
tasks:
  - name: Projektkurs-Mono
    init: |
      sudo mkdir /data
      sudo chown -R gitpod /data && sudo chmod u+rxw /data
      wget https://dl.min.io/server/minio/release/linux-amd64/minio
      chmod +x minio
      sudo chown -R gitpod /data && sudo chmod u+rxw /data
      MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=strongPassword ./minio server /data --console-address ":9001" &
      sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      sudo apt-get update -y
      sudo apt-get -y install postgresql pkg-config libssl-dev ffmpeg libpq-dev
      sudo systemctl stop postgresql.service
      sudo systemctl start postgresql.service
      sudo systemctl enable postgresql.service
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      rustup default nightly
      cargo install diesel_cli --no-default-features --features postgres 
    command: |
      echo "Hello to Projektkurs-Mono!"
