[global.databases]
postgres_logs = { url = "postgres://postgres:strongPassword@localhost/projekt" }

[release]
## Generate your own key using openssl with: "openssl rand -base64 32"
secret_key = "2MDLTHqMDMAxhoz/ZqduEkXu8xFEtmPh7XNtIeXy+Kg="
