streaming_mode: vod

# - 4k
resolutions:
  - 1080p
  - 720p
  - 480p
  - 360p

channel_layouts:
  - stereo
  - surround

# - opus
audio_codecs:
  - aac

# - vp9
video_codecs:
  - h264

manifest_format:
  - hls

# Length of each segment in seconds.
segment_size: 5

# Forces the use of SegmentTemplate in DASH.
segment_per_file: True
