# Streaming mode.  Can be live or vod.
streaming_mode: vod

# A list of resolutions to encode.
# For VOD, you can specify many more resolutions than you would with live,
# since the encoding does not need to be done in real time.
resolutions:
  - 4k
  - 1080p
  - 720p
  - 480p
  - 360p

# A list of channel layouts to encode.
channel_layouts:
  - stereo
  - surround

# The codecs to encode with.
audio_codecs:
  - aac
  - opus
video_codecs:
  - h264
  - vp9

# Manifest format (dash, hls or both)
manifest_format:
  - hls

# Length of each segment in seconds.
segment_size: 10

# Forces the use of SegmentTemplate in DASH.
segment_per_file: True
