[package]
name = "api-video"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "video_api"
path = "src/service.rs"

[dependencies]
log = "0.4.16"
rdkafka = { version = "0.26", features = ["cmake-build"] }
serde = "1.0.136"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
