apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      name: auth
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: msostream
        name: auth
        tier: backend
        track: stable
    spec:
      containers:
      - name: auth
        image: finnrg/msostream-auth:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:strongPassword@postgres-postgresql/auth"
        - name: JWT_SECRET
          value: "strongSecret"
        ports:
        - name: http
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    name: auth
    app: msostream
    tier: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000