apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: msostream
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: msostream
        tier: backend
        track: stable
    spec:
      containers:
      - name: msostream
        image: finnrg/backend:latest
        ports:
        - name: http
          containerPort: 8000