apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: msostream
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: msostream
        tier: frontend
        track: stable
    spec:
      containers:
      - name: frontend
        image: finnrg/msostream-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"

