apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    dev.okteto.com/generate-host: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-max-age: "600"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://msostream.io/"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type,authorization,x-grpc-web,grpc-timeout,keep-alive,user-agent,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Type,authorization,grpc-encoding,grpc-message,grpc-status"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy
            port:
              number: 8080
      - path: /upload
        pathType: Prefix
        backend:
          service:
            name: upload
            port:
              number: 8080
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /assets
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /stream
        pathType: Prefix
        backend:
          service:
            name: stream
            port:
              number: 8080