apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    dev.okteto.com/generate-host: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy
            port:
              number: 8080
      - path: /upload
        pathType: Prefix
        backend:
          service:
            name: upload
            port:
              number: 8080
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /assets
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /stream
        pathType: Prefix
        backend:
          service:
            name: stream
            port:
              number: 8080