apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream
spec:
  selector:
    matchLabels:
      name: stream
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: stream
        name: stream
        tier: backend
        track: stable
    spec:
      containers:
      - name: stream
        image: finnrg/msostream-stream:latest
        imagePullPolicy: Always
        env:
        - name: MINIO_URL
          value: http://minio:9000
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stream
spec:
  selector:
    name: stream
    app: stream
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http