ALTER TABLE videos DROP CONSTRAINT fk_user;
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users
ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE videos DROP COLUMN user_id;
ALTER TABLE videos
ADD COLUMN user_id Int;
ALTER TABLE videos
ADD CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id);