ALTER TABLE videos DROP CONSTRAINT fk_user;
ALTER TABLE users
ALTER COLUMN id TYPE CHAR(36);
ALTER TABLE videos
ALTER COLUMN user_id TYPE CHAR(36);
ALTER TABLE videos
ADD CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id);