name: ci-backend

on:
  push:
    branches:
      - 'main'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
  api-video:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: finnrg/msostream-api-video
          context: ./backend/api-video
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  auth:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: finnrg/msostream-auth
          context: ./backend/auth
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  packager:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: finnrg/msostream-packager
          context: ./backend/packager
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  upload:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: finnrg/msostream-upload
          context: ./backend/upload
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  stream:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: finnrg/msostream-stream
          context: ./backend/stream
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  search:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: finnrg/msostream-search
          context: ./backend/search
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  proxy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: finnrg/msostream-search
          context: ./conf/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    