name: ci-backend

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: finnrg/msostream-api-video
          context: ./backend/api-video
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
